/**
 * AUTO-GENERATED — do not edit manually.
 * Generated by scripts/generate-api-types.mjs from daemon OpenAPI spec.
 * To regenerate: node scripts/generate-api-types.mjs
 */

export const API_PATHS = [
  "/api/binaries/catalog",
  "/api/binaries/catalog/refresh",
  "/api/binaries/catalog/{app}",
  "/api/binaries/install",
  "/api/binaries/installed",
  "/api/binaries/installed/{app}",
  "/api/binaries/{app}/{version}",
  "/api/config/validate",
  "/api/databases",
  "/api/databases/{name}",
  "/api/databases/{name}/export",
  "/api/databases/{name}/import",
  "/api/databases/{name}/query",
  "/api/databases/{name}/size",
  "/api/databases/{name}/tables",
  "/api/dns/flush",
  "/api/events",
  "/api/php/versions",
  "/api/php/{version}/extensions",
  "/api/plugins",
  "/api/plugins/{id}/disable",
  "/api/plugins/{id}/enable",
  "/api/plugins/{id}/icon",
  "/api/plugins/{id}/ui",
  "/api/services",
  "/api/services/{id}",
  "/api/services/{id}/config",
  "/api/services/{id}/logs",
  "/api/services/{id}/restart",
  "/api/services/{id}/start",
  "/api/services/{id}/stop",
  "/api/services/{id}/validate-version",
  "/api/settings",
  "/api/sites",
  "/api/sites/reapply-all",
  "/api/sites/{domain}",
  "/api/sites/{domain}/detect-framework",
  "/api/sites/{domain}/history",
  "/api/sites/{domain}/rollback/{timestamp}",
  "/api/ssl/certs",
  "/api/ssl/certs/{domain}",
  "/api/ssl/generate",
  "/api/ssl/install-ca",
  "/api/status",
  "/api/system",
  "/healthz"
] as const

export type ApiPath = (typeof API_PATHS)[number]
